In [6]:
import numpy as np
from sklearn.linear_model import LinearRegression
import pandas as pd
import altair as alt
alt.renderers.enable('altair_viewer', inline=True)

RendererRegistry.enable('altair_viewer')

In [13]:
x = np.array([3,16,27,35,45,55]).reshape((-1,1))
y = np.array([5,20,24,32,22,38])

In [15]:
y

array([ 5, 20, 24, 32, 22, 38])

In [17]:
modelo = LinearRegression()

In [18]:
modelo.fit(x,y)

LinearRegression()

In [20]:
R_sq = modelo.score(x,y)

In [21]:
print("Coeficiente de derterminación:", round(R_sq , 2))
print("Intercepto (bo):", modelo.intercept_)
print("Pendiente  (b1):", modelo.coef_)

Coeficiente de derterminación: 0.75
Intercepto (bo): 7.998341472403945
Pendiente  (b1): [0.51386713]


In [22]:
x2 = np.array([4,16,25,37,45,85]).reshape((-1,1))

In [23]:
y_pred = modelo.predict(x2)

In [24]:
y_pred

array([10.05381001, 16.22021561, 20.84501981, 27.01142541, 31.12236248,
       51.67704782])

In [25]:
y_pred2 = modelo.predict(x)

In [26]:
y_pred2

array([ 9.53994287, 16.22021561, 21.87275408, 25.98369115, 31.12236248,
       36.26103382])

In [27]:
y 


array([ 5, 20, 24, 32, 22, 38])

In [29]:
df = pd.read_excel('data_regression.xlsx')

In [30]:
df 

Presion  Temperatura
0     1000        34.20
1     1100        39.80
2     1200        46.89
3     1300        51.90
4     1400        67.80
5     1500        71.60

In [31]:
df_x = df[['Presion']]
df_y = df[['Temperatura']]

In [32]:
df_x

Presion
0     1000
1     1100
2     1200
3     1300
4     1400
5     1500

In [33]:
df_modelo = LinearRegression()
df_modelo.fit(df_x,df_y)

LinearRegression()

In [36]:
df_R_sq = df_modelo.score(df_x,df_y)

In [38]:
print("Coeficiente de determinacion:", round(df_R_sq , 2))
print("Intercepto (bo):", df_modelo.intercept_)
print("Pendiente (b1) : ", df_modelo.coef_)

Coeficiente de determinacion: 0.97
Intercepto (bo): [-46.54333333]
Pendiente (b1) :  [[0.07886]]


In [39]:
df_y_pred=df_modelo.predict(df_x)
print(df_y_pred)

[[32.31666667]
 [40.20266667]
 [48.08866667]
 [55.97466667]
 [63.86066667]
 [71.74666667]]


In [40]:
df["Temperatura pred"]=df_y_pred
print(df)

   Presion  Temperatura  Temperatura pred
0     1000        34.20         32.316667
1     1100        39.80         40.202667
2     1200        46.89         48.088667
3     1300        51.90         55.974667
4     1400        67.80         63.860667
5     1500        71.60         71.746667


In [41]:
grafico = alt.Chart(df).mark_point().encode(
    x = "Presion",
    y = "Temperatura",
    tooltip = ['Presion','Temperatura']
).interactive()

In [42]:
grafico.display()

alt.Chart(...)

In [45]:
grafico_pred = alt.Chart(df).mark_line(color='red').encode(
    x= "Presion",
    y = "Temperatura pred"
).interactive()

In [46]:
grafico_pred.display()

alt.Chart(...)

In [47]:
graficos = alt.layer(grafico,grafico_pred)
graficos.display()

alt.LayerChart(...)